# Generated by Django 2.0.13 on 2020-03-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataXJob',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False, verbose_name='任务ID')),
                ('job_name', models.CharField(max_length=100, unique=True, verbose_name='任务名称')),
                ('job_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='任务描述')),
                ('read_instance_id', models.IntegerField(verbose_name='读取实例ID')),
                ('read_database', models.CharField(blank=True, max_length=255, verbose_name='读数据库名')),
                ('read_sql', models.TextField(verbose_name='读取sql内容')),
                ('writer_instance_id', models.IntegerField(verbose_name='写实例ID')),
                ('writer_database', models.CharField(blank=True, max_length=255, verbose_name='写数据库名')),
                ('writer_table', models.CharField(blank=True, max_length=255, verbose_name='写入表名')),
                ('writer_preSql', models.TextField(verbose_name='写入数据前执行的SQL语句')),
                ('writer_postSql', models.TextField(verbose_name='写入数据后执行的SQL语句')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('crate_user', models.CharField(max_length=100, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '数据同步任务',
                'verbose_name_plural': '数据同步任务',
                'db_table': 'datax_job',
                'managed': True,
            },
        ),
    ]
