# Generated by Django 2.0.13 on 2020-03-10 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataxweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataXJobWriterColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='列名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '写入表列信息',
                'verbose_name_plural': '写入表列信息',
                'db_table': 'datax_job_writer_column',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='dataxjob',
            name='writer_postSql',
            field=models.TextField(null=True, verbose_name='写入数据后执行的SQL语句'),
        ),
        migrations.AlterField(
            model_name='dataxjob',
            name='writer_preSql',
            field=models.TextField(null=True, verbose_name='写入数据前执行的SQL语句'),
        ),
        migrations.AddField(
            model_name='dataxjobwritercolumn',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataxweb.DataXJob'),
        ),
    ]
